CATEGORIES = {'2':'BASEBALL','4':'MOVIES','3':'ODD JOBS','11':'TRIVIA','15':'HOLLYWOOD LEGENDS',
              '16':'CARS','21':'ANIMALS','24':'MOVIE TRIVIA','25':'SCIENCE','32':'TOYS & GAMES'}
running = True
MAXQUESTIONS = 10
